### ISSUE TITLE
Frictional boundary

### ISSUE THREAD

**Issue by kks32** [cb-geo/mpm#20]
Handle friction boundary

**Comment by ezrayst** [comment]
Assigning myself for this (I cannot change the assignee and labels)

**Comment by ezrayst** [comment]
(1) The boundary will be implemented on surface of an element, instead of nodes
(2) Get the normal of the surface by cross product
(3) Acceleration and velocity of a particle undergo coordinate transformation to the new coordinate
(4) Compute calculation of the friction and transform back to Cartesian coordinate

Reference to old code: https://github.com/cb-geo/mpm-3d/blob/9db8f8663edfe173bf8ac3d031f86cc4129e9b93/cartesian/src/NodeMpm.ipp#L296
