### ISSUE TITLE
Frequent error message `No particles in cell, can't activate nodes` on all empty cells

### ISSUE THREAD

**Issue by ezrayst** [cb-geo/mpm#256]
Currently, the code outputs error messages for every empty cell. Since we will always have empty cells in a simulation (except element test), I think it's cleaner to omit this.

**Comment by kks32** [comment]
The error message you see is `No particles in cell, can't activate nodes`. This is defined in the cell class member function: `activate_nodes`. The reason why this as an error message is a potential problem is as the OP said there maybe multiple cells which are empty. Since this would mean the function will throw more often than not, I propose to change it to a void function with a try block. Although delegating the error as a trace could be an option, the frequency of error may result in multiple catch block executions, which will slow the code execution.
