### ISSUE TITLE
Particles belonging to which cell are not updated on each time step

### ISSUE THREAD

**Issue by ezrayst** [cb-geo/mpm#289]
**Observation**
Location of particles (in which cell) is not updated in each time step. 
The figure below shows this behavior. Note that the pressure is updated per cell so all particles in the same cell have the same pressure. In the figure, there are 25 particles per cell. Observe the bottom right corner: as most of the particles have crossed from one cell to another, the pressure (stress) is still computed as one.

**Proposed Solution**
We have to check all the particles whether they still belong to their current cells. Then use 
`cell`'s `add_particle_id` and `remove_particle_id` accordingly.

I personally think that it is more efficient to reset `particles_` in `cell` and use mesh's `locate_particles_mesh` in each time step.

**Comment by ezrayst** [comment]
![image](https://user-images.githubusercontent.com/22064721/46899992-0fa55880-ce50-11e8-8e67-fec901262b37.png)

**Comment by ezrayst** [comment]
I have made a small test case: two particles out of four cross the cell, but ownership has not changed. It can be seen [here](https://github.com/ezrayst/mpm/tree/check_cell/bin/2d_test). 

The video is shown in our slack page of how the particles cross the cell.

Results show that only Cell 0 (on the left) has 4 of the particles, but Cell 1 is not activated (and owns no particles where it should own 2)
![image](https://user-images.githubusercontent.com/22064721/46900213-842dc680-ce53-11e8-86e1-5f46bb1efcea.png)

**Comment by kks32** [comment]
The issue is because `reference_location` function which is used to get the reference location of a particle in natural coordinates doesn't check if particle is in cell, more precisely this line: https://github.com/cb-geo/mpm/blob/30c47c74b7e55c7ddcdafdc1e1aaae7881c35cb8/include/mesh.tcc#L236. 

The second issue was a missing lock_guard, which is cited here: https://github.com/cb-geo/mpm/blob/30c47c74b7e55c7ddcdafdc1e1aaae7881c35cb8/include/mesh.tcc#L223
