### ISSUE TITLE
Add numerical damping to explicit algorithm

### ISSUE THREAD

**Issue by srhgk2** [cb-geo/mpm#375]
**Numerical damping in the explicit algorithm**
Numerical damping is required to introduce energy dissipation (i.e. material damping) at low strain levels and to minimize spurious artificial oscillations in dynamic analysis. A damping term based on the classical Rayleigh damping is added to the momentum equilibrium equation as used in Bandara (2015). 

**Implementation**
***mpm_explicit.h file***
1. add Rayleigh damping coefficients to private variables
`double rayleigh_alpha_{0.}`
`double rayleigh_beta_{0.}`
2. store damping coefficients from json input file (if given)
3. call nodal function to compute the damping term

***node_base.h file***
add new virtual function to compute damping term
***node.h file & node.tcc***
1. define new variable `rayleigh_damp_`
2. add new function to compute the damping term
3. add `rayleigh_damp_` in `compute_acceleration_velocity` function

**Comment by kks32** [comment]
@thiagordonho Please start a new branch called `damping/cundall`

To implement `Cundall` damping. Define a JSON object as below
```
"damping" : {
   "type": "Cundall", 
   "damping_factor": 0.05
}
```
Parse this JSON object in the `MPMBase` class. In the `Node` class, define a new additional function called `compute_acceleration_velocity_cundall(double dt, double damping_factor)`. Please do not modify the existing `compute_acceleration_velocity` and leave it as is. The two separate functions mean we can check if the damping flag is on / off once per iteration of the solver in the `MPMExplicit` instead of checking for each node, which will offer better performance.

The damped acceleration is computed as:

```
damped_acceleration = -damping_factor_ * force.norm() * velocity.cwiseSign() / mass;
```

Eigen has `.cwiseSign()` function https://eigen.tuxfamily.org/dox/classEigen_1_1MatrixBase.html#title39 which allows you to get the sign of a function. 

We don't need to define a class separately for damping for now.
