### ISSUE TITLE
Consideration of a mesh reader library for the MPM code

### ISSUE THREAD

**Issue by kks32** [cb-geo/mpm#589]
**Describe the feature**
The ASCII mesh reader we have is a custom mesh file, and I found it hard to generate an input mesh file. It's not compatible with GMSH either. I'd suggest we look into supporting existing mesh file formats. 

**Describe alternatives**
Here are the following alternatives:
1. Read the latest GMSH format using GMSH as a shared library
2. Use MOAB: https://bitbucket.org/fathomteam/moab/src/master/ which is a library that has the capability to read different Mesh formats.
3. Try LibMesh: FE library which can read other Mesh formats as well. https://libmesh.github.io/doxygen/index.html

**Additional context** 
Thinking ahead, do we consider AMR for the future?

**Comment by cw646** [comment]
I find GMSH hexahedral meshes to be quite difficult to generate for a non-orthogonal shape and there are many limitations to it.

It shouldn't take too much effort to convert a Gmsh hex mesh to CB-Geo readable file though. 

Are there any free CAD tools that we can use instead? I could reach out to some CFD users to see what they use. I know openFoam has an inbuilt hex-mesh functionality (blockMesh) which can be combined with 'snappy hex mesh' for more complex shapes and localised refinement.

**Comment by ezrayst** [comment]
Personally, I feel that sticking to one type of file (or convention) would be great. 

Currently, we are using the GMSH numbering for the elements, but it is not exactly `.msh`. There are advantages of using GMSH v4 for example, that we can define entity of a mesh there. Nevertheless, our ASCII files are rather simple and easy to understand, which offers flexibility for users to create the mesh. 

Having said this, meshing will always be a problem (unless the problem is very structured). I have personally built my own tool box for this: sometimes my own codes, sometimes a combination of a few codes out there like salome and GMSH. But would future users like this? I don't know.

**Comment by kks32** [comment]
This is not about how we internally store the files in Mesh. This issue is mainly to discuss if we would like to support GMSH or other input file forms as IO. So, something like MOAB will be able to read these different formats, and we use iterators in MOAB to get the nodes and elements

**Comment by kks32** [comment]
After discussion, we plan to implement MOAB, first we check if MOAB supports finding boundaries. If boundaries are supported, then we go ahead with the implementation in a separate `moab` branch

**Comment by kks32** [comment]
As a decision has been made, I'm closing this issue will create a RFC/PR.
