### ISSUE TITLE
Automatic Dynamic Load Balancing

### ISSUE THREAD

**Issue by bodhinandach** [cb-geo/mpm#625]
**Describe the feature**
At the moment, I see that we are specifying the `nload_balance_steps_`. Wouldn't it be nice to make it automatic? 

**Describe alternatives**
Do `MPI_Gather` the `nparticles()` from each rank in rank 0 at the end of each step and judge there, e.g. we can make a limit on how many percents it is different to `nparticles()/mpi_size` to increase/reduce the automatic balancing frequency.

**Additional context**
This is particularly useful when simulating problems like landslides, where initially the particle moves rapidly, but in the end they are almost static and stop propagating. If we use a constant `nload_balance_steps_`, we will perform quite useless `domain_decomposition` at the end.

**Comment by kks32** [comment]
The `cell->nglobal_particles()` is basically a count across MPI ranks, so that would be sufficient to compute the load. We might also need to consider the number of shared nodes. The difficult part is not whether or not to do a load balancing, but for KaHIP to keep most of the partition the same, so the load balancing doesn't have to move a lot of particles. I noticed, between one partitioning to another it does change a lot, so I'm trying to see how to keep most of the partition the same.

**Comment by bodhinandach** [comment]
@kks32 I am reopening this. Are we going to take a look any time soon?
